### ISSUE TITLE
PA Review: Production README

### ISSUE THREAD

**Issue by amdrewnguyen** [amdrewnguyen/duabl#29]

**Comment by m1010j** [comment]
I'm getting 404s when I try to click on your gifs. Also, it might be a good idea to embed them directly.

**Comment by amdrewnguyen** [comment]
I'm updating my computer now so I can make the gifs. It'll be another 30
minutes though..

On Nov 3, 2017 11:24 AM, "m1010j" <notifications@github.com> wrote:

I'm getting 404s when I try to click on your gifs. Also, it might be a good
idea to embed them directly.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/amdrewnguyen/duabl/issues/29#issuecomment-341735474>,
or mute the thread

**Comment by amdrewnguyen** [comment]
Gifs are now embedded

**Comment by m1010j** [comment]
👍
