### ISSUE TITLE
PA Reivew: User Authentication

### ISSUE THREAD

**Issue by amdrewnguyen** [amdrewnguyen/duabl#43]

**Comment by m1010j** [comment]
I noticed that if I enter invalid credentials or sign up with a password that's too short, you don't render any errors. In fact, nothing happens on the page when I click submit, which would leave the user to think that the form isn't working.

**Comment by amdrewnguyen** [comment]
I just fixed this issue so that the returned errors render under the form.

**Comment by m1010j** [comment]
Almost fixed! You're using merge in your session errors reducer, which pushes new errors onto your errors array. As a result, when I enter invalid credentials twice, I get the same message twice. User Object.assign instead.

**Comment by amdrewnguyen** [comment]
Whoops, I just went ahead and set the state to action.errors. I think it works as intended now.

**Comment by m1010j** [comment]
Looks great now!
